{{- if .Values.tomcat.ingress.enabled -}}
{{- $fullName := include "intermine_instance.fullname" . -}}
{{- $ingressPaths := .Values.tomcat.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $fullName }}-ingress"
  labels:
    app.kubernetes.io/name: {{ include "intermine_instance.name" . }}
    helm.sh/chart: {{ include "intermine_instance.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.tomcat.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.tomcat.ingress.tls }}
  tls:
  {{- range .Values.tomcat.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.tomcat.ingress.hosts }}
    - host: {{ . | quote }}
    - http:
        paths:
	{{- range $ingressPaths }}
          - path: {{ . | quote }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 8080
	{{- end }}
  {{- end }}
{{- end }}
