apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intermine_instance.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "intermine_instance.name" . }}
    helm.sh/chart: {{ include "intermine_instance.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.tomcat.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "intermine_instance.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "intermine_instance.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.tomcat.image.repository }}:{{ .Values.tomcat.image.tag }}"
          imagePullPolicy: {{ .Values.tomcat.image.pullPolicy }}
          env:
          - name: "MEM_OPTS"
            value: "-Xmx256m -Xms128m"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.tomcat.livenessProbe.path }}
              port: {{ .Values.tomcat.service.port }}
            initialDelaySeconds: {{ .Values.tomcat.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.tomcat.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.tomcat.readinessProbe.path }}
              port: {{ .Values.tomcat.service.port }}
            initialDelaySeconds: {{ .Values.tomcat.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.tomcat.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.tomcat.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.tomcat.resources | nindent 12 }}
      {{- with .Values.tomcat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.tomcat.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tomcat.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
