# Default values for intermine_instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tomcat:
  name: intermine-tomcat
  replicaCount: 1
  image:
    repository: intermine/tomcat
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 256Mi
  readinessProbe:
    path: "/"
    initialDelaySeconds: 60
    periodSeconds: 30
    failureThreshold: 6
  livenessProbe:
    path: "/"
    initialDelaySeconds: 60
    periodSeconds: 30
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    enabled: true
    annotations:
      # kubernetes.io/ingress.class: nginx
      # nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
      # kubernetes.io/tls-acme: "true"
    paths: ["/"]
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

builder:
  name: intermine-builder
  replicaCount: 1
  image:
    repository: intermine/builder
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi

postgresql:
  name: postgresql
  port: "5432"
  postgresqlPassword: postgres
  persistence:
    size: 2Gi
  resources:
    limits:
      cpu: 250m
      memory: 600Mi
    requests:
      cpu: 250m
      memory: 256Mi

solr:
  name: solr
