# Default values for intermine_instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tomcat:
  name: intermine_tomcat
  replicaCount: 1
  image:
    repository: intermine/tomcat
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    enabled: true

builder:
  name: intermine_builder
  replicaCount: 1
  image:
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 500Mi

postgresql:
